server:
  port: ${PORT:8080}

spring:
  application:
    name: lottomazza

  config:
    import: optional:file:.env[.properties]

  data:
    mongodb:
      uri: ${MONGO_DB_URI}
      
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

logging:
  level:
    root: info
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{40} - %msg%n'
