server:
  port: ${PORT:8080}

spring:
  application:
    name: lottomazza

  config:
    import: optional:file:.env[.properties]

  data:
    mongodb:
      uri: ${MONGO_DB_URI}
      
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

